title: [Traitement vidéo]
description: [Ce cours permet à l’étudiante ou l’étudiant d’enregistrer, de modifier et de traiter des images en temps réel. L’étudiant sera appelé à appliquer des effets spéciaux aux images vidéo et à adapter les images en fonction de l’intégration.]

minima:
  skin: dark
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
